# -*- coding: utf-8 -*-
"""TMDB_Collections.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/122A4szknmJAYt2QBoYvLilPcR4JSedqf
"""

import requests
import gzip
import json
import concurrent.futures
from datetime import datetime, timedelta, timezone
from google.colab import files

# 1. Get user API Key (Use your standard API Key from TMDB settings)
API_KEY = input("Enter your TMDB API Key: ").strip()
params = {"api_key": API_KEY}

# 2. Download the Collections export file
now_utc = datetime.now(timezone.utc)
yesterday = (now_utc - timedelta(days=1)).strftime('%m_%d_%Y')
today = now_utc.strftime('%m_%d_%Y')

# Corrected URL for TMDB daily data exports
base_export_url = "https://files.tmdb.org/p/exports/"

url = f"{base_export_url}collection_ids_{yesterday}.json.gz"
response = requests.get(url, stream=True)

if response.status_code != 200:
    url = f"{base_export_url}collection_ids_{today}.json.gz"
    response = requests.get(url, stream=True)

with open("collection_ids.json.gz", "wb") as f:
    f.write(response.content)

# 3. Extract Collection IDs
collection_ids = []
with gzip.open("collection_ids.json.gz", "rb") as f:
    for line in f:
        try:
            collection_ids.append(json.loads(line.decode('utf-8'))['id'])
        except Exception:
            continue

print(f"Found {len(collection_ids):,} total collections. Fetching movie details...")

final_output = []

# 4. Fetch movies inside each collection
def fetch_collection_parts(collection_id):
    # Corrected URL for TMDB API collection details
    url = f"https://api.themoviedb.org/3/collection/{collection_id}"
    try:
        # Changed headers to params for reliable free API auth
        res = requests.get(url, params=params, timeout=5)
        if res.status_code == 200:
            data = res.json()
            parts = []
            for movie in data.get("parts", []):
                # 👈 FILTER ADDED: Skip the movie if TMDB flags 'adult' as True
                if movie.get("adult") is True:
                    continue

                parts.append({
                    "id": movie["id"],
                    "title": movie["title"],
                    "collection": {
                        "id": data["id"],
                        "name": data["name"],
                        "poster_path": data.get("poster_path"),
                        "backdrop_path": data.get("backdrop_path")
                    }
                })
            return parts
    except Exception:
        pass
    return []

# Use multithreading to parse the collections quickly
with concurrent.futures.ThreadPoolExecutor(max_workers=20) as executor:
    results = executor.map(fetch_collection_parts, collection_ids)
    for result in results:
        if result:
            final_output.extend(result)

# Save to format
output_file = "collection_movies.json"
with open(output_file, "w", encoding="utf-8") as f:
    json.dump(final_output, f, indent=4, ensure_ascii=False)

print(f"Finished! Total franchise movies mapped: {len(final_output):,}")
files.download(output_file)